#!/usr/bin/perl -T

use warnings;
use strict;
use lib qw(lib);
use admin_app::controller;
use admin_app::decor;
use admin_app::util;
use admin_app::view::error;


our $VERSION = do { my ($r) = q$LastChangedRevision: 413 $ =~ /(\d+)/smx; $r; };

main();
0;

sub main {
  my $util = admin_app::util->new();
  admin_app::controller->handler($util);
}
 
