#!/usr/bin/perl -T

use warnings;
use strict;
use lib qw(lib);
use ClearPress::controller;

use admin_app::util;
use admin_app::view::error;

use admin_app::view::holiday;
use admin_app::model::holiday;
use admin_app::view::expense_claim;
use admin_app::model::expense_claim;
use admin_app::view::responsibility_for;
use admin_app::model::responsibility_for;
use admin_app::view::admingroup;
use admin_app::model::admingroup;
use admin_app::view::person_admingroup;
use admin_app::model::person_admingroup;
use admin_app::view::person;
use admin_app::model::person;
use admin_app::view::person_allowance;
use admin_app::model::person_allowance;
use admin_app::view::team;
use admin_app::model::team;
use admin_app::view::person_team;
use admin_app::model::person_team;

our $VERSION = do { my ($r) = q$LastChangedRevision: 413 $ =~ /(\d+)/smx; $r; };

main();
0;

sub main {
  my $util = admin_app::util->new();
  ClearPress::controller->handler($util);
}
 
